### ISSUE TITLE
Task 3 -  New features in quizzes

### ISSUE THREAD

**Issue by B1ackMambaX** [B1ackMambaX/JavaTelegramBot#11]
## Формулировка задачи:

1. Добавить квизы по другим языкам программирования. Пример диалога: 
П: `/quiz`
Б: `Выбери ЯП по которому хочешь пройти тест: Java, JS, Python, C++`. (Внизу у пользователя отображаются кнопки)
2. Добавить логгер для вывода событий и ошибок.
3.  Разделить ответ бота на несколько сообщений в тех местах, где сообщения содержат разную тематику. Пример подобных сообщений:  
До: `Вы ответили правильно! Какой метод удаляет последний элемент массива?`
После: `Вы ответили правильно!`     `Какой метод удаляет последний элемент массива?`
4. Добавить вывод статистики после завершения квиза. Пример: `Тест закончен! Количество правильных ответов 10 из 20`
5. Кастомизация надписей на кнопках, вынесение ответов на основные команды в отдельный класс.

**Comment by vpyzhyanov** [comment]
> Добавить квизы по другим языкам программирования

Этот функционал должен быть расширяемым. Пожалуйста, учтите это при разработке.

> Разделить ответ бота на несколько сообщений в тех местах, где сообщения содержат разную тематику. Пример подобных сообщений:
До: Вы ответили правильно! Какой метод удаляет последний элемент массива?
После: Вы ответили правильно! Какой метод удаляет последний элемент массива?

Что изменилось?

> Кастомизация надписей на кнопках, вынесение ответов на основные команды в отдельный класс.

Не понял что это значит

А в целом хорошо.

**Comment by vpyzhyanov** [comment]
> Добавить квизы по другим языкам программирования. Пример диалога:
> П: /quiz
> Б: Выбери ЯП по которому хочешь пройти тест: Java, JS, Python, C++. (Внизу у пользователя отображаются кнопки)
> Добавить логгер для вывода событий и ошибок.
> Добавить вывод статистики после завершения квиза. Пример: Тест закончен! Количество правильных ответов 10 из 20

**Согласовано**. Оставил для согласования только самое важное, всё остальное опционально.
