### ISSUE TITLE
Task 4: Statistics

### ISSUE THREAD

**Issue by B1ackMambaX** [B1ackMambaX/JavaTelegramBot#15]
## Формулировка задачи

1. Добавить команду `/mystats` которая показывает статистику пользователя.
2. Добавить команду `/leaderboard` которая показывает лидерборд из всех пользователей по каждому из ЯП и общий.

## Примеры диалогов
1. П: `/mystats`
    Б: Ваша статистика: 
            JavaScript: 11/20
            Python: 5/20
            Общая: 16/40
2. П: `/leaderboard`
     Б: Выберите какой лидерборд хотите посмотреть <Внизу у пользователя показываются кнопки>
     П: JavaScript
     Б: Лидерборд по JavaScript:
         1. b1ackmambax 20/20
         2. some user 14/20
         3. begenFys 1/20

**Comment by vpyzhyanov** [comment]
И ни слова о том, как этот админский доступ получить. Это нужно описать.

**Comment by vpyzhyanov** [comment]
> Формулировка задачи
> Добавить команду /mystats которая показывает статистику пользователя.
> Добавить команду /leaderboard которая показывает лидерборд из всех пользователей по каждому из ЯП и общий.
> Примеры диалогов
> П: /mystats
> Б: Ваша статистика:
> JavaScript: 11/20
> Python: 5/20
> Общая: 16/40
> П: /leaderboard
> Б: Выберите какой лидерборд хотите посмотреть <Внизу у пользователя показываются кнопки>
> П: JavaScript
> Б: Лидерборд по JavaScript:
> 1. b1ackmambax 20/20
> 2. some user 14/20
> 3. begenFys 1/20

согласовано
