### ISSUE TITLE
Task 2 - Update Architecture

### ISSUE THREAD

**Issue by begenFys** [B1ackMambaX/JavaTelegramBot#5]
# Задача 2 - Обновление архитектуры

**Основная задача:** Обновить архитектуру проекта, чтобы сделать поддержку многопользовательского режима у ботов, классы ботов формировать из интерфейса Bot. Идеи реализация многопользовательского режима:

- Хранить экземпляры логики для каждого пользователя в Hashmap в классе бота
- Реализовать менеджер состояний бота (конечный автомат)
- Реализовать клавиатуру для команд
<img width="500" alt="Снимок экрана 2023-10-13 в 22 42 25" src="https://github.com/B1ackMambaX/JavaTelegramBot/assets/114356998/285d8a95-4a05-42b8-b424-68554c112fa5">

**Подзадача:** Реализация хранения данных в базе данных PostgreSQL, конкретная реализация:

1. ORM
2. Асинхронного подключение к базе

**Подзадача со свёздочкой:** Деплой через Docker, намётки на CI/CD, конкретная реализация:

1. Dockerfile для контейнера приложения
2. docker-compose файл для одновременного поднятия БД и приложения

### Пример диалога:

***Б:*** Привет я DeveloperHelperBot, я могу помочь тебе отточить твои теоретические знания о языке JavaScript. Для того чтобы начать введи /quiz. В ответ на вопрос введи только одно слово
***Пользователь 1:*** /quiz
***Б:*** Тест по ЯП JavaScript, состоит из 10 вопросов. Как правильно задать наследование одного класса от другого?
***Пользователь 1:*** extends
***Б:***  Отлично, это правильный ответ! (либо в случае неправильного ответа: Неправильно! Правильный ответ: extends)

***Пользователь 2(во время теста Пользователя 1):*** Ты кто такой?!?!?
**Б:** Я не понимаю вас, посмотреть список доступных комманд можно с помощью /help

## Возможные пути расширения функционала

- Добавление админ-панели через которую можно добавлять новые вопросы.
- Добавление статистики внутри “личного кабинета” пользователя.
- Добавление разделов с полезными статьями по различным ЯП.
- Добавление лидерборда.
- Добавление разбиения вопросов по тематикам.
- Добавление доступа к [API предоставляющей расписание контестов по программированию](https://kontests.net/api)  с таких платформ как LeetCode, Codeforces, etc.
- Добавление доступа к  [API компилирующему и выполняющему код.](https://ce.judge0.com/)
- Добавление доступа к [API новостей](https://newsapi.org/), которая будет присылать новости о технологиях.

**Comment by vpyzhyanov** [comment]
По сути всё описание задачи состоит из обязательных требований и доп. баллов. Нужно добавить что-то существенное в саму задачу. Например можно реализовать конечный автомат для смены состояний бота.

**Comment by vpyzhyanov** [comment]
> Основная задача: Обновить архитектуру проекта, чтобы сделать поддержку многопользовательского режима у ботов, классы ботов формировать из интерфейса Bot. Идеи реализация многопользовательского режима:
> Хранить экземпляры логики для каждого пользователя в Hashmap в классе бота
> Реализовать менеджер состояний бота (конечный автомат)
> Реализовать клавиатуру для команд

Согласовано
